---

#
# install openjdk
#

- name: Update the apt cache
  apt:
    cache_valid_time: 3600
    update_cache: yes

- name: Install OpenJDK packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ jdk_packages }}"
  when: "{{ jdk_packages }}"


- name: set JAVA_HOME
  template:
    src: jdk.sh
    dest: /etc/profile.d/jdk.sh
